name: trainer_manager_pro
description: "A trainer-focused fitness management app with clean architecture"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.4.1

  # Code Generation
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

  # Backend & Auth
  supabase_flutter: ^2.7.0

  # UI & Navigation
  go_router: ^14.6.2
  flutter_svg: ^2.0.16
  cached_network_image: ^3.4.1

  # Forms & Validation
  flutter_form_builder: 10.0.1
  form_builder_validators: ^11.0.0

  # Utils
  intl: ^0.19.0
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  dartz: ^0.10.1

  # Video Calling & Real-time
  # agora_rtc_engine: ^6.3.2  # Temporarily disabled due to C++ linking issues
  zego_uikit_prebuilt_video_conference: ^2.9.9
  socket_io_client: ^2.0.3+1
  
  # File handling & Media
  file_picker: ^8.1.2
  video_player: ^2.9.2
  chewie: ^1.8.5
  
  # Real-time features
  web_socket_channel: ^3.0.1
  
  # Additional UI
  flutter_chat_ui: ^1.6.15
  emoji_picker_flutter: ^3.1.0
  
  # Notifications
  flutter_local_notifications: ^18.0.1
  
  # Utils for video
  path_provider: ^2.1.4
  uuid: ^4.5.1
  flex_color_scheme: ^8.2.0
  google_fonts: ^6.2.1
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # Code Generation
  build_runner: ^2.4.13
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  riverpod_generator: ^2.4.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
